package com.example.maola.yummifragment.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATEGORIE_DB".
*/
public class CategorieDBDao extends AbstractDao<CategorieDB, Long> {

    public static final String TABLENAME = "CATEGORIE_DB";

    /**
     * Properties of entity CategorieDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NomeCategoria = new Property(1, String.class, "nomeCategoria", false, "NOME_CATEGORIA");
        public final static Property ImmagineCategoria = new Property(2, int.class, "immagineCategoria", false, "IMMAGINE_CATEGORIA");
    }

    private DaoSession daoSession;


    public CategorieDBDao(DaoConfig config) {
        super(config);
    }
    
    public CategorieDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATEGORIE_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NOME_CATEGORIA\" TEXT," + // 1: nomeCategoria
                "\"IMMAGINE_CATEGORIA\" INTEGER NOT NULL );"); // 2: immagineCategoria
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATEGORIE_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CategorieDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nomeCategoria = entity.getNomeCategoria();
        if (nomeCategoria != null) {
            stmt.bindString(2, nomeCategoria);
        }
        stmt.bindLong(3, entity.getImmagineCategoria());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CategorieDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nomeCategoria = entity.getNomeCategoria();
        if (nomeCategoria != null) {
            stmt.bindString(2, nomeCategoria);
        }
        stmt.bindLong(3, entity.getImmagineCategoria());
    }

    @Override
    protected final void attachEntity(CategorieDB entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CategorieDB readEntity(Cursor cursor, int offset) {
        CategorieDB entity = new CategorieDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nomeCategoria
            cursor.getInt(offset + 2) // immagineCategoria
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CategorieDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNomeCategoria(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImmagineCategoria(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CategorieDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CategorieDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CategorieDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
