package com.example.maola.yummifragment.Database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.maola.yummifragment.Database.CategorieDB;
import com.example.maola.yummifragment.Database.SalvateDB;

import com.example.maola.yummifragment.Database.CategorieDBDao;
import com.example.maola.yummifragment.Database.SalvateDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categorieDBDaoConfig;
    private final DaoConfig salvateDBDaoConfig;

    private final CategorieDBDao categorieDBDao;
    private final SalvateDBDao salvateDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categorieDBDaoConfig = daoConfigMap.get(CategorieDBDao.class).clone();
        categorieDBDaoConfig.initIdentityScope(type);

        salvateDBDaoConfig = daoConfigMap.get(SalvateDBDao.class).clone();
        salvateDBDaoConfig.initIdentityScope(type);

        categorieDBDao = new CategorieDBDao(categorieDBDaoConfig, this);
        salvateDBDao = new SalvateDBDao(salvateDBDaoConfig, this);

        registerDao(CategorieDB.class, categorieDBDao);
        registerDao(SalvateDB.class, salvateDBDao);
    }
    
    public void clear() {
        categorieDBDaoConfig.clearIdentityScope();
        salvateDBDaoConfig.clearIdentityScope();
    }

    public CategorieDBDao getCategorieDBDao() {
        return categorieDBDao;
    }

    public SalvateDBDao getSalvateDBDao() {
        return salvateDBDao;
    }

}
